syntax = "proto3";

package chat;

message Envelope {
  oneof payload {
    Ping ping = 1;
    Pong pong = 2;
    SendMessage send_message = 3;
    MessageDelivered message_delivered = 4;
    Ack ack = 5;
    TypingEvent typing_event = 6;
    PresenceState presence_state = 7;
    SendFile send_file = 8;
    FileDelivered file_delivered = 9;
  }
}

message Ping {}
message Pong {}

message SendMessage {
  string room_id = 1;
  bytes content = 2;
}

message MessageDelivered {
  string room_id = 1;
  int64 sequence_number = 2;
  string sender_id = 3;
  bytes content = 4;
  int64 inserted_at = 5;
}

message Ack {
  int64 sequence_number = 1;
  string room_id = 2;
}

message TypingEvent {
  string room_id = 1;
  string user_id = 2;
  bool is_typing = 3;
}

message PresenceState {
  repeated string user_ids = 1;
}

message SendFile {
  string room_id = 1;
  string file_key = 2;
  string filename = 3;
  string content_type = 4;
  int64 size = 5;
}

message FileDelivered {
  string room_id = 1;
  int64 sequence_number = 2;
  string sender_id = 3;
  string file_key = 4;
  string filename = 5;
  string content_type = 6;
  int64 size = 7;
  int64 inserted_at = 8;
}
